### ISSUE TITLE
Database Output

### ISSUE THREAD

**Issue by jelmerdeboer** [rpjproost/Context-project-Health-informatics-2#47]
Can someone explain exactly, where the database stores the answers, how it is stored and what will be stored?

**Comment by wimspaargaren** [comment]
Hi Jelmer, I hope I understand everything correctly, but here it goes. In the XML is per document a docname specified. This docname will be the table name. Then we have per column in the file which is parsed a name which probably is the column name and a type which is Integer, String etc. So if you have a look at the goodXML file in test->data->xml->goodXML.xml it should create a table named stat, with 3 columns named value(integer), date(String) and time(String).
These values are stored from the parse methods in TXT and Excel parser which call the insert method of the DB class. I hope everything's clear if not let me know!
